//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ExamsEntities : DbContext
    {
        public ExamsEntities()
            : base("name=ExamsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChiefExpert> ChiefExpert { get; set; }
        public virtual DbSet<Exam> Exam { get; set; }
        public virtual DbSet<Expert> Expert { get; set; }
        public virtual DbSet<Organizer> Organizer { get; set; }
        public virtual DbSet<Participant> Participant { get; set; }
        public virtual DbSet<Skill> Skill { get; set; }
    }
}
