//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.Drawing;
    using System.IO;

    public partial class Expert
    {
        public int IdExpert { get; set; }
        public string FullName { get; set; }
        public string Sex { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Passport { get; set; }
        public string Photo { get; set; }
        public string IdSkill { get; set; }
    
        public virtual Skill Skill { get; set; }

        public Image PhotoImage
        {
            get
            {
                var filename = Path.Combine(Environment.CurrentDirectory, "Эксперты", Photo);

                if (File.Exists(filename))
                {
                    return Image.FromFile(filename);
                }
                return null;
            }
        }
    }
}
